### PR TITLE
What fucking idiot made outcasts spawn with t5 guns and armor?

### PR DESCRIPTION
**Pull request by ghost**
Outcast numbers dropped to 6, so that paired with the khans, there's 12 raiders

Outcast guns reduced to t1 or t2 guns

Outcast armor will be reduced later when I take a look at armor values

### CODE REVIEW

**Comment by KillerGryphon** [comment]
LMAO they are meant to have these, to give them an early advantage. It has been this way for a looooooong long time.

**Comment by ghost** [comment]
@KillerGryphon They don't need an early advantage and Desert Rose's powercreep of guns and armor infesting the entire server has been a significant detriment to everything.

At the moment, outlaws literally outclass NCR troopers and legionnaires in both guns and armor, since NCR armor is worse than raider armor and their guns are also standard or worse.

Spawning with *laser pistols* and *trench shotguns*? Nope.

**Comment by Pebblesthe2nd** [comment]
I kind of like it, using the lower end of the spectrum stuff more makes the game more interesting, not less. I'd say try it out for a week and get a feel for it, outlaws been pretty powerful so far, needs some sort of balancing in my view, and this is one way to do it.

**Comment by KillerGryphon** [comment]
> I kind of like it, using the lower end of the spectrum stuff more makes the game more interesting, not less. I'd say try it out for a week and get a feel for it, outlaws been pretty powerful so far, needs some sort of balancing in my view, and this is one way to do it.

This balancing is already done by the vigilante role. We want to balance? Reduce the slots amount.

**Comment by Pebblesthe2nd** [comment]
Mm maybe, looking at the details some stuff is a bit iffy with the single shotgun and whatnot. Needs a closer look.

**Pull request merged**
