### PR TITLE
NCR partial rework

### PR DESCRIPTION
**Pull request by KillerGryphon**
## About The Pull Request

After lots of hours when I should be sleeping, I have completed a rework that covers some of the issues the NCR has had from what players have told me. In short, the NCR Captain and Heavy Trooper have been re-added to the game, and a counterpart for the Medical Officer, the Logistics Officer, who is in charge of engineering matters on base, has been added to the game, and a small office attached to the armory has been added for the LO as well. The Captain has two reworked loadouts, which comes with a choice of armor and weapons. The LT also has a Heavy Service Rifle now, hurrah!

EDIT: As requested, here are the map changes, just a small attached office: https://i.imgur.com/hPHZgng.png

## Why It's Good For The Game

NCR has lacked their main leadership role since this server has started, and has an all too baseline loadout all the way up to the LT, service rifles galore. This PR aims to change that, reintroducing a new specialist role, the Heavy Trooper, and adding back their CO, the Captain, in charge of the LT and the Veteran Ranger both, and adding an additional leadership role for Engineer Troops, the Logistics Officer, who is more techy and is in charge of base defense and more (detailed in their starting text). The HT is equipped with a LMG, salvaged NCR Power Armor that has had it's speed buffed to match the speeds of similar armor like the raiders and hotrod armors, and their helmet has been given a new coat of paint as well, no mistaking them for regular salvaged, that's for sure! Lastly, the XO of Camp Miller should have a slightly better gun, according to their rank, and so they've been buffed to the R82 from the Service Rifle, because gun diversity was desperately needed in the NCR (although we're not stepping outside of 5.56).

## Changelog
:cl:
add: Added back Captain, Heavy Trooper roles, added Logistics Officer, new Engineering Officer role.
add: Small office for the LO attached to the armory!
del: Removed small table outside of armory removed to make room for the above office!
tweak: tweaked armor block and slowdown of NCR Power armor, armor block is slightly higher, and Slowdown is far less, because it was just extreme before.
balance: added R82 to LT loadout, considering they were higher rank, but didn't have a better gun!
fix: fixed LT armor values being improperly marked as VII when they were only VI.
code: Added code for Captain loadouts, flags, spawning for all ranks, and entirely built Heavy Trooper and Logistics Officer in code.
/:cl:

### CODE REVIEW

**Comment by thedarkcrusader** [comment]
post pictures of  the map changes on the PR please

**Comment by ValoTheValo** [comment]
good changes. Captain is needed and HTs are a good addition

**Comment by faaaay** [comment]
Most of this seems neat, but with regards to Logistics Officer - I don't know if it's necessary. There's only one Combat Engineer; they'd only be commanding a single person. Honestly, it may be worth replacing the Combat Engineer with Logistics Officer entirely. There's not much engineering to do in combat anyway.

**Comment by KillerGryphon** [comment]
> post pictures of the map changes on the PR please

Done! Check the edit in the PR and imgur link

**Comment by KillerGryphon** [comment]
> Most of this seems neat, but with regards to Logistics Officer - I don't know if it's necessary. There's only one Combat Engineer; they'd only be commanding a single person. Honestly, it may be worth replacing the Combat Engineer with Logistics Officer entirely. There's not much engineering to do in combat anyway.

Hi Faaaay, thank you for the support! Logistics officer was a suggestion by more than one NCR player, and they are the counter part to the Medical Officer, who also has only one medic. As I said in the PR, the LO is in charge of base defense, and knows more recipes for weapons, and comes with a toolbelt of advanced tools to do their work better. I personally believe there is a chance for the LO to become viable, and they should be given the chance to shine before being commented away. As an alternative, what would you say to INCREASING the slots by one for the medic and engineers, to make their Officers more needed?

**Comment by KillerGryphon** [comment]
> good changes. Captain is needed and HTs are a good addition

Thank you Valo, the NCR players have long been wanting this, and while I personally don't play NCR, these roles sound right up my alley, so I sure hope they're good!

**Pull request merged**
