### PR TITLE
Revert "What fucking idiot made outcasts spawn with t5 guns and armor?"

### PR DESCRIPTION
**Pull request by KillerGryphon**
Reverts nokele/desertrose#70

Massive debate regarding this in discord RN, public opinion says nay, complete removal of the BoS Outcast? Replacing a trench gun... with a single shotgun, with beanbags? Not the way to go by far.

### CODE REVIEW

**Comment by Mannybrado** [comment]
I don't get how you can give vigilante explosive ammo and a set of the best armor in the game, then say that the best weapon raiders are given being a fireaxe is overpowered. 
EVERYONE is given tier 4+ shit round start. At the VERY LEAST, decrease their weapons but increase their slots. There's no fucking reason at all to decrease their slots in the first place, a group of raiders surpassing 3 or 4 is incredibly rare. The argument that raiders are OP is genuinely fucking mind-boggling to me, but maybe I'm not a total fucking idiot.
PLEASE merge this. What the fuck, man.

**Comment by Mannybrado** [comment]
BoS outcast is retarded though, for real. HONESTLY, all of the outcast roles are, but whatever.

**Comment by ProfessorPopoff** [comment]
I don't know if you were present in this community two years ago, but i'll let you in on a secret. The Town itself in the storage thing under the shop has more resources than the ENTIRE MAP had on it back on BD, and it gave people something to work towards. I'm not even going to mention all the weapons, crafting parts, crafting benches, blueprints, and gun books they start with. The more that you continue to pump in high tier gear to roundstart roles in this code, the worse it's going to get. What are they going to do with all this gear they're given? Stand around...? Talk? Talk about how they wish they were 'back home' and wait until some wastelander walks in their general direction, only to immediately unload every gun they have one them because 'they were coming at them aggressively?'

All this could be excused if a "Roleplay Server"'s community didn't lack basic imagination. I mean- Vigilante role? What happened to making your own fate as a wastelander? Who are they employed by? Themselves? That's just wastelander role given a ton of gear by some moron that wanted to not work for anything. 

This entire codebase is littered with powercreep in every inch and crevice. There needs to be more of an effort towards nerfing things. The previous PR should be taken at face value. A start to fix what previous servers horribly broke.

Anyways. Rant concluded. If you don't gather anything from my autistic rambling, sure. Go ahead and continue as you were with... Whatever autist balancing this in. TLDR: Quit the powercreep. Let the nerf happen. There's no reason for them to have this stuff.

**Comment by ghost** [comment]
@mannybrado

I'm against the vigilante getting the explosive ammo either.

We need to start somewhere with reducing powercreep, like the guy above said.  And yes, there is reason to decrease their slots, there's fifteen raiders and six khans, they usually tend to outnumber factions in sheer size and yet still spawn with decent gear which excaberates metarushing.

Less raiders = less problem. 6 raiders, 6 khans. That's 12 raiders total for the round. A sizeable amount, i'd say.

**Pull request closed without merging**
