### PR TITLE
readds the 3 second delay to applying healing powder

### PR DESCRIPTION
**Pull request by ghost**
Why was it removed?

### CODE REVIEW

**Comment by Mannybrado** [comment]
Because healing powder is dogshit. Can you at least make the recipe back to 1 broc and 1 xander? DR made it fucking 3 each.

**Comment by ghost** [comment]
> Because healing powder is dogshit. Can you at least make the recipe back to 1 broc and 1 xander? DR made it fucking 3 each.

If Kelo sees fit to merge this, I will

**Comment by ErwinSnowden** [comment]
> > Because healing powder is dogshit. Can you at least make the recipe back to 1 broc and 1 xander? DR made it fucking 3 each.
> 
> If Kelo sees fit to merge this, I will

Why not just commit the changes in the PR to make it more seamless?

**Comment by FantasticFwoosh** [comment]
> 
> 
> > > Because healing powder is dogshit. Can you at least make the recipe back to 1 broc and 1 xander? DR made it fucking 3 each.
> > 
> > 
> > If Kelo sees fit to merge this, I will
> 
> Why not just commit the changes in the PR to make it more seamless?

I was going to suggest the same thing; while the PR is open you can continue adding commits to it if you simply upload changes to your published forked-remote branch.

**Comment by ghost** [comment]
because i'm fuckng superstitious about making prs that are large in any way shape or form because withotu fail every single fucking time i do it turns out that the original content of the pr is something that the headcoder chooses to have an autistic shitfit over and closes it for which then wastes my time

**Comment by nokele** [comment]
do the same for stims and such to make it even. Superstims and poultice can have a lower delay of like 1 second to make them more desirable.

**Comment by ghost** [comment]
@nokele they are already desirable being that they *heal more*-making an item that heals better also faster to apply simply skews it further in their favor

**Comment by ogrigbe** [comment]
Stimpaks of all kinds are instantly applied. I see no reason to make powders have a time to apply to further fuck the legion. Sorry no.

**Comment by ghost** [comment]
@ogrigbe I can just make stimpacks have a time before injection as well.

**Pull request closed without merging**
