### PR TITLE
makes vigilante not stupid

### PR DESCRIPTION
**Pull request by ghost**
who the fuck thought t7 armor was a good idea

### CODE REVIEW

**Comment by nokele** [comment]
Kinda intended to be stupid in case of bad men doing too much bad men stuff

**Comment by ProfessorPopoff** [comment]
One issue with this PR, Adam. You didn't just remove the Vigilante role.

**Comment by special1kira** [comment]
good question

**Comment by ogrigbe** [comment]
Going to need you to describe what it is, what it changes and why it's good for the game.

**Comment by ghost** [comment]
Waste of time.

**Pull request closed without merging**
