### PR TITLE
Pahrump Overhaul 

### PR DESCRIPTION
**Pull request by Keksk**
## About The Pull Request:
This PR is an overhaul of Pahrump. Mainly focusing on adding old content back and moving Oasis further to the center of the map.

## Why It's Good For The Game

Moving Oasis further into the center instead of the corner will make it easier for people to use it as a hub to roleplay in. Legion might be closer to it and have more incentive to enslave the population of Oasis, creating conflict where the NCR would be able to step in and do their job.
The followers clinic has been merged into the Oasis doctor , since nobody even plays Oasis doctor and it’s basically the same role.Kinda retarded they were right next to eachother anyway.
More bunkers because it’s fun.

## Changelog
:cl:
add: 3 old bunkers in second z-level 
add: new independent church south to oasis
add: new oasis
balance: loot has lesser tier the less risk it requires
balance: shopkeeper only has tier 7-8 instead of 9-10
del: oasis church 
del: nuked oasis doctor
del: followers clinic
del: old oasis

## Notes:
Might need more testing in regards to balance.

## Screenshots:
( Zoom in for Original size )

https://i.ibb.co/hLJ8kZJ/1.png

https://i.ibb.co/jgKN6vq/2.png

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
If you have pictures to spare it'd help the rest of us understand the scope of it.

**Comment by Keksk** [comment]
## Before 
( zoom in )

https://i.ibb.co/CKr0Mym/3.png

https://i.ibb.co/cxGh3K3/4.png


## After
( also zoom in )

https://i.ibb.co/hLJ8kZJ/1.png

https://i.ibb.co/jgKN6vq/2.png

**Comment by thedarkcrusader** [comment]
the other entrance to the new  town does not have a checkpoint

**Comment by Keksk** [comment]
> 
> 
> the other entrance to the new town does not have a checkpoint




Added another checkpoint

**Comment by Pebblesthe2nd** [comment]
A lot of the described changes sounds very similar to what I've been thinking needs doing, so if the mappers/maintainers ensure its quality I am all for it. Needs to be checked against the south map rework thats been discussed porting from DR maybe. 
In concept I love it, I hope its well implemented.

**Comment by Megarop** [comment]
> The followers clinic has been merged into the Oasis doctor , since nobody even plays Oasis doctor
Nobody plays follower doctor either.

**Comment by KillerGryphon** [comment]
> > The followers clinic has been merged into the Oasis doctor , since nobody even plays Oasis doctor
> 
> Nobody plays follower doctor either.

Not sure why you say this, I've seen plenty of people play them at peak times, some even main the role.

**Comment by KillerGryphon** [comment]
Hi there! Overall, interesting changes! I AM in favor of bringing Oasis out of the corner and making it more central, but I have a few issues with the redesign. 

1. I do appreciate you taking into account my redesign of Oasis and expanded the gunshop lobby, but I'm sad to see you didn't consider the same for places like the bar, which is now entirely shrinked, lacks a brahmin, and now the newly added inn rooms are gone. Sink there isn't even against the wall, and a wooden tile is there, out of place clearly. 
2. The "hidden" entrance to oasis, right below the bar, is FAR too easy an entry point. The easiest way to get into current oasis outside of entering the front gate, is by cutting two rusted metal girders apart. As far as I can see, you just need to walk through water and walk through a vent shaft here. Bad security for the town that could endanger them.
3. The farm. I am not entirely sure why you have the plant grow areas like that, you couldn't line them up? I like it being in town, and the addition of a bedroom for them, but the decision to place them like that is.... strange. Also, you've neglected to place another brahmin and chicken there. There are two of each so that they can be bred by the Farmer.
4. Absolutely no above ground living locations. One of the ideal parts of being in the corner of the map is that you have room to expand in that won't interfere with the rest of the map. This isn't the case here, and I see you've compensated by removing ALL above ground living locations for townies, the only beds being those in the medbay... and the farmers, which you've added. Not all the townies should have to live under ground.
5. The Prospectors. They're the mining role for town, and even have their own ore redemption machine! I want you to look at where they were, and the ore mining opportunities they could access, and where they are now... aka, in the middle of the sewers, trapped, with no ore to mine.
6. EDIT: I almost didn't notice! You COMPLETELY removed Oasis Church, and the Oasis Oak. The Oasis Oak is where Oasis got it's name, removing that just makes it a fuck all town in the middle of no where. Adding a church south of Oasis is completely butchering the role, and making them disconnected from the town utterly. It's the OLD Oasis church, just... outside of town, far too outside.

I haven't even mentioned the complete removal of the followers you've done, a decision I completely disagree with, but that doesn't apply to the town itself. 

Overall, a firm **no** to this PR until all of the above issues are addressed.

**Comment by Megarop** [comment]
> Not sure why you say this, I've seen plenty of people play them at peak times, some even main the role.

Yeah, that was anecdotal evidence and it was stupid of me to say that.

I think the oasis doctor role is worth keeping even though the followers are right next to oasis so people can play as a doctor without having to follow the values of the followers that say to preach humanitarianism and heal both sides of every conflict and give people free education and save the poor or whatever.

If there's no other wasteland doctor role (the loadout doesn't count), people might end up playing follower doctor without actually acting like a follower because they just want to be a regular doctor.

**Comment by Keksk** [comment]
> 
> 
> Hi there! Overall, interesting changes! I AM in favor of bringing Oasis out of the corner and making it more central, but I have a few issues with the redesign.
> 
>     1. I do appreciate you taking into account my redesign of Oasis and expanded the gunshop lobby, but I'm sad to see you didn't consider the same for places like the bar, which is now entirely shrinked, lacks a brahmin, and now the newly added inn rooms are gone. Sink there isn't even against the wall, and a wooden tile is there, out of place clearly.
> 
>     2. The "hidden" entrance to oasis, right below the bar, is FAR too easy an entry point. The easiest way to get into current oasis outside of entering the front gate, is by cutting two rusted metal girders apart. As far as I can see, you just need to walk through water and walk through a vent shaft here. Bad security for the town that could endanger them.
> 
>     3. The farm. I am not entirely sure why you have the plant grow areas like that, you couldn't line them up? I like it being in town, and the addition of a bedroom for them, but the decision to place them like that is.... strange. Also, you've neglected to place another brahmin and chicken there. There are two of each so that they can be bred by the Farmer.
> 
>     4. Absolutely no above ground living locations. One of the ideal parts of being in the corner of the map is that you have room to expand in that won't interfere with the rest of the map. This isn't the case here, and I see you've compensated by removing ALL above ground living locations for townies, the only beds being those in the medbay... and the farmers, which you've added. Not all the townies should have to live under ground.
> 
>     5. The Prospectors. They're the mining role for town, and even have their own ore redemption machine! I want you to look at where they were, and the ore mining opportunities they could access, and where they are now... aka, in the middle of the sewers, trapped, with no ore to mine.
> 
>     6. EDIT: I almost didn't notice! You COMPLETELY removed Oasis Church, and the Oasis Oak. The Oasis Oak is where Oasis got it's name, removing that just makes it a fuck all town in the middle of no where. Adding a church south of Oasis is completely butchering the role, and making them disconnected from the town utterly. It's the OLD Oasis church, just... outside of town, far too outside.
> 
> 
> I haven't even mentioned the complete removal of the followers you've done, a decision I completely disagree with, but that doesn't apply to the town itself.
> 
> Overall, a firm **no** to this PR until all of the above issues are addressed.

1. I don't see why the bar requires everything built in. If the barkeeper wants to slaughter Brahmin he'll have to go interact with other players, such as the farmer or whoever has cattle at the very moment. I have stripped a few things because I have deemed them to be less than useful. I don't think every bar on the map should offer housing. Most of it is used for ERP and I don't think the Server wants that to be the main focus. 

2. Yeah, I think that'll needs to be fixed.

3. I didn't even see the lining up the fields as a problem lmao. Once again, if the farmer wants a second pair he'll have to go outside and get himself another pair. More for him to do.

4. There can be living spaces added but I don't see them having any purpose.

5. Guess they'll actually have to pick up their equipment and head outside instead of staying within the towns border. There is a new mine placed where Oasis once was and a perfect place for them to mine. I did forget their ore redemption machine lmao 

6. I'll move the old church and oak underneath new-Oasis into the sewer with the oak being the center piece.

Why would the followers have such a big operation in Pahrump. I'd give them a seperate base further away from Oasis.

**Comment by KillerGryphon** [comment]
> > Hi there! Overall, interesting changes! I AM in favor of bringing Oasis out of the corner and making it more central, but I have a few issues with the redesign.
> > ```
> > 1. I do appreciate you taking into account my redesign of Oasis and expanded the gunshop lobby, but I'm sad to see you didn't consider the same for places like the bar, which is now entirely shrinked, lacks a brahmin, and now the newly added inn rooms are gone. Sink there isn't even against the wall, and a wooden tile is there, out of place clearly.
> > 
> > 2. The "hidden" entrance to oasis, right below the bar, is FAR too easy an entry point. The easiest way to get into current oasis outside of entering the front gate, is by cutting two rusted metal girders apart. As far as I can see, you just need to walk through water and walk through a vent shaft here. Bad security for the town that could endanger them.
> > 
> > 3. The farm. I am not entirely sure why you have the plant grow areas like that, you couldn't line them up? I like it being in town, and the addition of a bedroom for them, but the decision to place them like that is.... strange. Also, you've neglected to place another brahmin and chicken there. There are two of each so that they can be bred by the Farmer.
> > 
> > 4. Absolutely no above ground living locations. One of the ideal parts of being in the corner of the map is that you have room to expand in that won't interfere with the rest of the map. This isn't the case here, and I see you've compensated by removing ALL above ground living locations for townies, the only beds being those in the medbay... and the farmers, which you've added. Not all the townies should have to live under ground.
> > 
> > 5. The Prospectors. They're the mining role for town, and even have their own ore redemption machine! I want you to look at where they were, and the ore mining opportunities they could access, and where they are now... aka, in the middle of the sewers, trapped, with no ore to mine.
> > 
> > 6. EDIT: I almost didn't notice! You COMPLETELY removed Oasis Church, and the Oasis Oak. The Oasis Oak is where Oasis got it's name, removing that just makes it a fuck all town in the middle of no where. Adding a church south of Oasis is completely butchering the role, and making them disconnected from the town utterly. It's the OLD Oasis church, just... outside of town, far too outside.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I haven't even mentioned the complete removal of the followers you've done, a decision I completely disagree with, but that doesn't apply to the town itself.
> > Overall, a firm **no** to this PR until all of the above issues are addressed.
> 
> 1. I don't see why the bar requires everything built in. If the barkeeper wants to slaughter Brahmin he'll have to go interact with other players, such as the farmer or whoever has cattle at the very moment. I have stripped a few things because I have deemed them to be less than useful. I don't think every bar on the map should offer housing. Most of it is used for ERP and I don't think the Server wants that to be the main focus.
> 2. Yeah, I think that'll needs to be fixed.
> 3. I didn't even see the lining up the fields as a problem lmao. Once again, if the farmer wants a second pair he'll have to go outside and get himself another pair. More for him to do.
> 4. There can be living spaces added but I don't see them having any purpose.
> 5. Guess they'll actually have to pick up their equipment and head outside instead of staying within the towns border. There is a new mine placed where Oasis once was and a perfect place for them to mine. I did forget their ore redemption machine lmao
> 6. I'll move the old church and oak underneath new-Oasis into the sewer with the oak being the center piece.
> 
> Why would the followers have such a big operation in Pahrump. I'd give them a seperate base further away from Oasis.

1. It's not a "built in" issue, it's a "starting with basic items" issue. Like I said in my 3., you don't even have enough brahmin to breed starting off. This is again a "starting with basic items" issue. Round start setup shouldn't include basic things for the role. In addition, "every bar"? We are talking about Oasis bar. IDK where the hell this "Most of it is used for ERP" is coming from considering it was JUST added, so, you need to think about it some more.
2. I am happy you see this issue.
3. See 1., "lol go do it yourself" shouldn't be a thing here. Not to mention, the only other chickens on the map are in the Chiken Ranch, guarded by raider mobs. Farmers shouldn't have to go through that if they want to produce eggs. Also, at least making it look nice should be a priority as a mapper.
4. It's a town. Why wouldn't it have living spaces???? There are roles that exclusively use those living spaces.
5. Again, "lol go do it yourself" is NOT a valid change. You neutered them completely, and gutted the role from their prime resource. It'd be like taking the farmer and saying "Farm? Go find a farm lol we're not gonna provide it for you" which is not smart in any sense.
6. The enclave base is RIGHT south of Oasis, I don't see this being possible.
7. They were put there BECAUSE of how needed they were on the map, I remember it from DR, too few doctors, but people wanted to PLAY doctors. The followers was the solution. You don't need them next to Oasis, but replacing Oasis doc with them is not wise, the Oasis med center is NOT large enough for an entire minor faction like the Followers.

**Comment by Keksk** [comment]
## New Changes

https://i.ibb.co/brZzmCg/6.png

https://i.ibb.co/XjNxcWR/5.png

**Comment by Keksk** [comment]
> 
> 
> > > Hi there! Overall, interesting changes! I AM in favor of bringing Oasis out of the corner and making it more central, but I have a few issues with the redesign.
> > > ```
> > > 1. I do appreciate you taking into account my redesign of Oasis and expanded the gunshop lobby, but I'm sad to see you didn't consider the same for places like the bar, which is now entirely shrinked, lacks a brahmin, and now the newly added inn rooms are gone. Sink there isn't even against the wall, and a wooden tile is there, out of place clearly.
> > > 
> > > 2. The "hidden" entrance to oasis, right below the bar, is FAR too easy an entry point. The easiest way to get into current oasis outside of entering the front gate, is by cutting two rusted metal girders apart. As far as I can see, you just need to walk through water and walk through a vent shaft here. Bad security for the town that could endanger them.
> > > 
> > > 3. The farm. I am not entirely sure why you have the plant grow areas like that, you couldn't line them up? I like it being in town, and the addition of a bedroom for them, but the decision to place them like that is.... strange. Also, you've neglected to place another brahmin and chicken there. There are two of each so that they can be bred by the Farmer.
> > > 
> > > 4. Absolutely no above ground living locations. One of the ideal parts of being in the corner of the map is that you have room to expand in that won't interfere with the rest of the map. This isn't the case here, and I see you've compensated by removing ALL above ground living locations for townies, the only beds being those in the medbay... and the farmers, which you've added. Not all the townies should have to live under ground.
> > > 
> > > 5. The Prospectors. They're the mining role for town, and even have their own ore redemption machine! I want you to look at where they were, and the ore mining opportunities they could access, and where they are now... aka, in the middle of the sewers, trapped, with no ore to mine.
> > > 
> > > 6. EDIT: I almost didn't notice! You COMPLETELY removed Oasis Church, and the Oasis Oak. The Oasis Oak is where Oasis got it's name, removing that just makes it a fuck all town in the middle of no where. Adding a church south of Oasis is completely butchering the role, and making them disconnected from the town utterly. It's the OLD Oasis church, just... outside of town, far too outside.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I haven't even mentioned the complete removal of the followers you've done, a decision I completely disagree with, but that doesn't apply to the town itself.
> > > Overall, a firm **no** to this PR until all of the above issues are addressed.
> > 
> > 
> > 
> > 1. I don't see why the bar requires everything built in. If the barkeeper wants to slaughter Brahmin he'll have to go interact with other players, such as the farmer or whoever has cattle at the very moment. I have stripped a few things because I have deemed them to be less than useful. I don't think every bar on the map should offer housing. Most of it is used for ERP and I don't think the Server wants that to be the main focus.
> > 2. Yeah, I think that'll needs to be fixed.
> > 3. I didn't even see the lining up the fields as a problem lmao. Once again, if the farmer wants a second pair he'll have to go outside and get himself another pair. More for him to do.
> > 4. There can be living spaces added but I don't see them having any purpose.
> > 5. Guess they'll actually have to pick up their equipment and head outside instead of staying within the towns border. There is a new mine placed where Oasis once was and a perfect place for them to mine. I did forget their ore redemption machine lmao
> > 6. I'll move the old church and oak underneath new-Oasis into the sewer with the oak being the center piece.
> > 
> > Why would the followers have such a big operation in Pahrump. I'd give them a seperate base further away from Oasis.
> 
>     1. It's not a "built in" issue, it's a "starting with basic items" issue. Like I said in my 3., you don't even have enough brahmin to breed starting off. This is again a "starting with basic items" issue. Round start setup shouldn't include basic things for the role. In addition, "every bar"? We are talking about Oasis bar. IDK where the hell this "Most of it is used for ERP" is coming from considering it was JUST added, so, you need to think about it some more.
> 
>     2. I am happy you see this issue.
> 
>     3. See 1., "lol go do it yourself" shouldn't be a thing here. Not to mention, the only other chickens on the map are in the Chiken Ranch, guarded by raider mobs. Farmers shouldn't have to go through that if they want to produce eggs. Also, at least making it look nice should be a priority as a mapper.
> 
>     4. It's a town. Why wouldn't it have living spaces???? There are roles that exclusively use those living spaces.
> 
>     5. Again, "lol go do it yourself" is NOT a valid change. You neutered them completely, and gutted the role from their prime resource. It'd be like taking the farmer and saying "Farm? Go find a farm lol we're not gonna provide it for you" which is not smart in any sense.
> 
>     6. The enclave base is RIGHT south of Oasis, I don't see this being possible.
> 
>     7. They were put there BECAUSE of how needed they were on the map, I remember it from DR, too few doctors, but people wanted to PLAY doctors. The followers was the solution. You don't need them next to Oasis, but replacing Oasis doc with them is not wise, the Oasis med center is NOT large enough for an entire minor faction like the Followers.

1. My point still stands. Every bar on the map includes a way of housing. So why would someone prefer one bar over another if they are pretty much the same aside from location. It just adds variety.

3. Okay and when did I mention that. There have been multiple points for brahmin and chicken added. Even then those raider mobs are easily taken care of. And if by chance the farmer doesn't think he can handle the AI, he can ask his fellow town people. 

4. You need to chill lol You even mentioned it having living spaces beneath. I don't see the issue.

5. I don't see the issue. Let them work for it. It's a 1 minute stroll to the nearest mine.

**Comment by Hyperstellarwithguns** [comment]
> 1. It's not a "built in" issue, it's a "starting with basic items" issue. Like I said in my 3., you don't even have enough brahmin to breed starting off. This is again a "starting with basic items" issue. Round start setup shouldn't include basic things for the role. In addition, "every bar"? We are talking about Oasis bar. IDK where the hell this "Most of it is used for ERP" is coming from considering it was JUST added, so, you need to think about it some more.
> 2. I am happy you see this issue.
> 3. See 1., "lol go do it yourself" shouldn't be a thing here. Not to mention, the only other chickens on the map are in the Chiken Ranch, guarded by raider mobs. Farmers shouldn't have to go through that if they want to produce eggs. Also, at least making it look nice should be a priority as a mapper.
> 4. It's a town. Why wouldn't it have living spaces???? There are roles that exclusively use those living spaces.
> 5. Again, "lol go do it yourself" is NOT a valid change. You neutered them completely, and gutted the role from their prime resource. It'd be like taking the farmer and saying "Farm? Go find a farm lol we're not gonna provide it for you" which is not smart in any sense.
> 6. The enclave base is RIGHT south of Oasis, I don't see this being possible.
> 7. They were put there BECAUSE of how needed they were on the map, I remember it from DR, too few doctors, but people wanted to PLAY doctors. The followers was the solution. You don't need them next to Oasis, but replacing Oasis doc with them is not wise, the Oasis med center is NOT large enough for an entire minor faction like the Followers.

my man you really gotta chill out, this ain't a very good look. not to mention; farmers really SHOULD have to work for their stuff, it's the post apocalypse man. smh my head

**Comment by Megarop** [comment]
> farmers really SHOULD have to work for their stuff, it's the post apocalypse man. smh my head

It's a video game man, it's supposed to be fun even if it's about something that wouldn't be fun in real life, shaking my head
Besides, I don't see why the apocalypse would've made it any harder for a farmer to put his farmland in a straight line or find a cow before the round starts.

> I don't see the issue. Let them work for it. It's a 1 minute stroll to the nearest mine.

A 60 second walk to the NEAREST mine and then another 60 second walk back every single time you want to go mining or deposit your ores sounds like a pain in the butt.

**Comment by nokele** [comment]
downloaded the files and merging manually because conflicts.

**Pull request closed without merging**
