### PR TITLE
all mobs beat you to death in crit now

### PR DESCRIPTION
**Pull request by ghost**
No more healig out of crit constantly and soloing a dungeon-mobs will finish you off in crit. Bring a buddy!

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
These don't have to be enabled by default, and would probably be much more usefully implemented on higher level mobs than the typical radroach, for the power-spike they give. It also poses that it could be its own cheese mechanic to have mobs dwell on certain individuals too long as "bait" with high phyiscal resist armor values preventing them from instantly dying or drugs rather than focus on wiping out the team.

Using fakedeath zombie-powder/ghoul-powder to trick low level mobs with a fake critical condition while you heal up from serious damage, would be a powerful strategy that can be retained with such a change.

**Comment by githubuser4141** [comment]
> No more healig out of crit constantly and soloing a dungeon-mobs will finish you off in crit. Bring a buddy!

Why not make it so only high-level dungeon mobs do this? This'd make things pretty awful for those with bad connections or who aren't very robust and I just don't see how wasteland tier mobs beating people to permadeath makes things more fun.

**Comment by KillerGryphon** [comment]
Big disagree with this change, too punishing to have it on ALL mobs. The mobs that need this, have it.

**Comment by ghost** [comment]
Since you're all idiots, wastebot only then.

**Pull request closed without merging**
