### PR TITLE
All chems blacklisted, then adds around 50 to whitelist.

### PR DESCRIPTION
**Pull request by bigpep**
## About The Pull Request
This blacklists all of the chems, then I whitelisted around 50. All default chem-dispenser chems, anything that was already allowed to be synth'd, and a few drugs. I can add anything as needed.

## Why It's Good For The Game
Players can be punished for lore-break for using chems from strange-seeds.

## Changelog
:cl:
tweak: Only certain chems come from strange seeds.
/:cl:

### CODE REVIEW

**Comment by bigpep** [comment]
Forgot to say but this was for botany, technically also odyessus chem synth but mechs aren't used.

**Comment by ghost** [comment]
This is a pretty bad idea. You're going to break a LOT of shit with this.

**Comment by bigpep** [comment]
> 
> 
> This is a pretty bad idea. You're going to break a LOT of shit with this.

How? This var is only used by odyessus synth and random plant chem generation. Am I misunderstanding something?

**Comment by ogrigbe** [comment]
Be more clear and concise of EXACTLY what this does please without me having to go into the code and review what you've changed.

**Comment by bigpep** [comment]
> 
> 
> Be more clear and concise of EXACTLY what this does please without me having to go into the code and review what you've changed.

Fair enough, this sets the reagent variable "can_synth" to false, this variable affects two things, random chemical picking, and odysseus chem synth. Random chemical picking is only used for seven things, none of which are frequently seen, this doesn't break any of them. This change makes it so only around 60 chemicals have can_synth set to true. When a strange seed picks a random chemicals for it to have, it can only be one of those 60 chemicals. Previously, it was probably in the hundreds due to TG chem bloat, much of which could get a player warned or punished for lore-break, such as the flight potion. My idea was that allowing chemicals that players can make normally, would encourage them to make wanted chemicals themselves by mixing traits.

**Pull request closed without merging**
