### PR TITLE
Legion Rework

### PR DESCRIPTION
**Pull request by Pebblesthe2nd**
Final Version.

## About The Pull Request

https://imgur.com/a/pwyul6h   (Loadouts pic)
https://imgur.com/a/PIMaIEz (Chain of command overview)

Rework of Legion to A) keep balance with NCR and the general move towards lower tier weapons and B) add variety and Legion spirit to improve RP environment, and C) reduce clutter and legacy homebrew stuff that isn't necessary.

Weapon loadouts are all redone. See the overview above.
Slots added, Legion sit at 22 combatants and 2 armed support roles, and 6 civilian support roles with this. (from 18 + 1 +10)
(NCR currently at 26 combatants, 6 armed support, and couple civilian support for comparison.)

Forgemaster moved from Auxilia and put into Camp Duty role with Slavemaster, temporary legionaire assignment.
Sort of camp defense/support role, also a form of off duty. Good 1 slot mains who want to do other stuff too for once.
Fewer latin names in the titles. Latin is better used as spice, sparingly outside whats already in the lore.
Traits overhaul: Vex, Prime, Rec Decan gets Hard yards. To keep with the glass cannon concept.
Every support role either has teachings of Mars or tinkering or low surgery to be able to give a little more variety in tasks.

1 clip of armor piercing ammo given to each Decanus, to give counter to PA enemies.
Vexillarius repurposed as specialist, given some AP ammo, intended to focus on PA enemies for now. Loadout will change accordingly.
Auxilia relabeled as Household Slaves and branded. Not other mechanical change, but slots dropped to 2.
Venator gone : its a officer role who rarely lead, basically just a role to get NVG, small armor boost and a sniper rifle.  Explorers take orders from Vet Dec and Centurion now instead, and got a time lock to weed out total rookies. Instead Explorers get a big bonus with c-4 and smoke bomb to hopefully change they way they are played.
Priestess gone: Legate does all that role can do, and keeping with role bloat its gone.
Camp Followers removed since they overlap with slave and auxilia, also Follower as title when a faction Legion hates has the 
same monicker is unneeded confusion.
Orator was aleady commented out so just finalized it, same deal.
Slavemaster moved from its own role to the kinda off duty/defense role as mentioned.
Slaves get small boost in traits/kit, one more slot and small timelock so newbies get to try Recruit first to actually learn a little about Legion RP before getting murdered for being a bad slave. Its a support role, requires a little RPing to work and not be a detriment.

Recipes for Legion culture stuff moved to the Forgemaster, recipes adjusted a little to keep weapons of similar power comparable in cost and also use silver for spatha to make it a little more special.

## Why It's Good For The Game

A lot of people got opinions on loadouts. This is a compromise and no one who advised got all they wanted, so I think its a solid move. Gives Legion a healthy base to build from and refine from here, free from a lot of baggage. Its trying to emphasis assymetrical balance and finding other solutions than one for one equivalents.

## Changelog
:cl:
add: Traits for all support roles in Legion added/tweaked.
add: Roles added: Camp duty (camp stationed soldiers who help defend and do some support stuff.)
del: Roles removed: Priestess, Orator, Venator, Camp Follower. Reduce bloat and overlap.
tweak: Loadouts changed for all Legion roles to add weapon variety while keeping with the goal of lower tiers. Auxilia now labeled Household slaves.
tweak: Recipes for Legion culture weapons made and locked to only Forgemaster. Gladius, spatha, lance, roman shield. Also added a trail carbine to same role for now.
fix: Typo in gladius recipe. Added metal glaive recipe (needs a tiny follow up PR that will come when this is merged.)
/:cl:

### CODE REVIEW

**Comment by Pebblesthe2nd** [comment]
Currently trying to fix the issue with Camp duty and Slaves spawning on the street, last issue AFAIK before its ready.

**Comment by ghost** [comment]
Legion needs their own counterpart to the heavy trooper.

**Comment by Pebblesthe2nd** [comment]
> Legion needs their own counterpart to the heavy trooper.

Not going to give Legion PA, and theres already 11 roles that really cant be slimmed down further. A 12th is an option I'm keeping open to make a well founded decision, not a band aid fix to counter some new addition thats still being tweaked.
I am however toying with repurposing the Vex a specialist, in this case, maybe giving him some AP weapons, together with a small amount of AP ammo for some decanus role. Thats the kind of role purpose that can be adapted by loadouts and small changes further down the road.

I heavily dislike the design philosphy for a organization with many 1 slot roles without being necessary, it too easily ends up with a mess of snowflakes that dont work together. Thats part of why I feel 12 roles is the absolute max. TL: DR  - there will only be one role added to the regular roster, and its not going to be a clone of anything NCR has. Armor busting vex is what I am tinkering with, got a better idea, lets hear it. If I agree I will include it.

**Comment by Mannybrado** [comment]
> > Legion needs their own counterpart to the heavy trooper.
> 
> Not going to give Legion PA, and theres already 11 roles that really cant be slimmed down further. A 12th is an option I'm keeping open to make a well founded decision, not a band aid fix to counter some new addition thats still being tweaked.
> I am however toying with repurposing the Vex a specialist, in this case, maybe giving him some AP weapons, together with a small amount of AP ammo for some decanus role. Thats the kind of role purpose that can be adapted by loadouts and small changes further down the road.
> 
> I heavily dislike the design philosphy for a organization with many 1 slot roles without being necessary, it too easily ends up with a mess of snowflakes that dont work together. Thats part of why I feel 12 roles is the absolute max. TL: DR - there will only be one role added to the regular roster, and its not going to be a clone of anything NCR has. Armor busting vex is what I am tinkering with, got a better idea, lets hear it. If I agree I will include it.

A "heavy" legionary like the previous libritor goes against the Legion's combat doctrine anyways, not that anyone cares.
The only thing I don't like about this PR is that Auxilia still exists, but........... whatever. This is great otherwise.

**Comment by Mannybrado** [comment]
Oh, also, mirror balancing is for bitches, ADAM.

**Comment by Pebblesthe2nd** [comment]
> Oh, also, mirror balancing is for bitches, ADAM.

(quoted the wrong reply but this turned out more comical so leaving it in)

I'm glad you mentioned Auxilia. Never quite like the way slaves transition from slave to auxilia, a frontline camp should not really be freeing more slaves than they capture. Made them household slaves instead, long time slaves with extra training, makes total sense. This way you get natural promotion path possible, if necessary, reduce confusion is status of civilians in the Legion camp (they are now ALL slaves) and also, a honestly unneeded homebrew thing is removed. Mechanically its still the same, RP wise its not a huge change, and while doing all the other changes no reason to not fix this while at it. Just waiting for the map vars linter crud to be fixed serverside before its submitted. Tweaking will no doubt be needed since its a ton of stuff in this PR but it'll be sorted as it appears.

**Comment by Pebblesthe2nd** [comment]
I'm sure there will be some issues but I suggest merging and giving it a week before further changes, at least unless something is obviously broken.

**Pull request merged**
